### ISSUE TITLE
Body parts rendering in the wrong places

### ISSUE THREAD

**Issue by Nirguy** [InventivetalentDev/MineRender#27]
Hi, as I mentioned on the discord server, some body parts in the skin renderer are displayed in the wrong place, and some of the faces are flipped or rotated.

It happens with all the skins, its just unnoticeable for most of them because the legs and arms are usually almost mirrored and the flipped faces are mostly hidden.

I used the skin below to check what parts are messed up and i made a list of them, which is in the attached file.
The white parts of the skin should always be on the right and the blue parts on the left. The red letters should be displayed on the correct face and not flipped. On the bottom and top faces, the 2 red pixels should be closer to the left side and the front side of the skin.
![image](https://user-images.githubusercontent.com/20445070/70573475-bb5c4c80-1baa-11ea-9a8a-3a9c44fd22c4.png)

[MineRender Wrong Parts.docx](https://github.com/InventivetalentDev/MineRender/files/3947433/MineRender.Wrong.Parts.docx)

**Comment by Andre601** [comment]
I can confirm this.

**Comment by InventivetalentDev** [comment]
Should be fixed now, let me know if there are still issues!

**Comment by Andre601** [comment]
It is partially fixed, but still displays the top part of the head wrongly.

How it renders:
![image](https://user-images.githubusercontent.com/11576465/77774077-c7c9bf80-704a-11ea-8350-3e20b0d30b43.png)

How it should render:
![image](https://user-images.githubusercontent.com/11576465/77774105-d3b58180-704a-11ea-889b-b0c12feb17bf.png)

**Comment by InventivetalentDev** [comment]
Hmm, that's weird.  
I've tested all faces and their orientation quite extensively. This is directly from Skindex's editor -> MineRender:
![](https://yeleha.co/2vTue1L)  
![](https://yeleha.co/2vWR2O8)

**Comment by Andre601** [comment]
I think this is fixed.
I myself couldn't see any other wrong display with the skins.
